//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion_Caja_Hospital.SN {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paciente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Paciente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdPacienteField;
        
        private int ValorCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoIdentidadField;
        
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        private float DeudaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        private bool ActivoField;
        
        private System.DateTime FechaRegistroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdPaciente {
            get {
                return this.IdPacienteField;
            }
            set {
                if ((this.IdPacienteField.Equals(value) != true)) {
                    this.IdPacienteField = value;
                    this.RaisePropertyChanged("IdPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ValorCodigo {
            get {
                return this.ValorCodigoField;
            }
            set {
                if ((this.ValorCodigoField.Equals(value) != true)) {
                    this.ValorCodigoField = value;
                    this.RaisePropertyChanged("ValorCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DocumentoIdentidad {
            get {
                return this.DocumentoIdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoIdentidadField, value) != true)) {
                    this.DocumentoIdentidadField = value;
                    this.RaisePropertyChanged("DocumentoIdentidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public float Deuda {
            get {
                return this.DeudaField;
            }
            set {
                if ((this.DeudaField.Equals(value) != true)) {
                    this.DeudaField = value;
                    this.RaisePropertyChanged("Deuda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SN.PacientesSoap")]
    public interface PacientesSoap {
        
        // CODEGEN: Generating message contract since element name Nombres from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarPacientes", ReplyAction="*")]
        Aplicacion_Caja_Hospital.SN.InsertarPacientesResponse InsertarPacientes(Aplicacion_Caja_Hospital.SN.InsertarPacientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarPacientes", ReplyAction="*")]
        System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.InsertarPacientesResponse> InsertarPacientesAsync(Aplicacion_Caja_Hospital.SN.InsertarPacientesRequest request);
        
        // CODEGEN: Generating message contract since element name Nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pacientecaja", ReplyAction="*")]
        Aplicacion_Caja_Hospital.SN.pacientecajaResponse pacientecaja(Aplicacion_Caja_Hospital.SN.pacientecajaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pacientecaja", ReplyAction="*")]
        System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.pacientecajaResponse> pacientecajaAsync(Aplicacion_Caja_Hospital.SN.pacientecajaRequest request);
        
        // CODEGEN: Generating message contract since element name Paciente from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loginPacientecaja", ReplyAction="*")]
        Aplicacion_Caja_Hospital.SN.loginPacientecajaResponse loginPacientecaja(Aplicacion_Caja_Hospital.SN.loginPacientecajaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loginPacientecaja", ReplyAction="*")]
        System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.loginPacientecajaResponse> loginPacientecajaAsync(Aplicacion_Caja_Hospital.SN.loginPacientecajaRequest request);
        
        // CODEGEN: Generating message contract since element name pacientes from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarPaciente", ReplyAction="*")]
        Aplicacion_Caja_Hospital.SN.RegistrarPacienteResponse RegistrarPaciente(Aplicacion_Caja_Hospital.SN.RegistrarPacienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarPaciente", ReplyAction="*")]
        System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.RegistrarPacienteResponse> RegistrarPacienteAsync(Aplicacion_Caja_Hospital.SN.RegistrarPacienteRequest request);
        
        // CODEGEN: Generating message contract since element name Nombres from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AumentarCuenta", ReplyAction="*")]
        Aplicacion_Caja_Hospital.SN.AumentarCuentaResponse AumentarCuenta(Aplicacion_Caja_Hospital.SN.AumentarCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AumentarCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.AumentarCuentaResponse> AumentarCuentaAsync(Aplicacion_Caja_Hospital.SN.AumentarCuentaRequest request);
        
        // CODEGEN: Generating message contract since element name Nombres from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PagarCuenta", ReplyAction="*")]
        Aplicacion_Caja_Hospital.SN.PagarCuentaResponse PagarCuenta(Aplicacion_Caja_Hospital.SN.PagarCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PagarCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.PagarCuentaResponse> PagarCuentaAsync(Aplicacion_Caja_Hospital.SN.PagarCuentaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarPacientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarPacientes", Namespace="http://tempuri.org/", Order=0)]
        public Aplicacion_Caja_Hospital.SN.InsertarPacientesRequestBody Body;
        
        public InsertarPacientesRequest() {
        }
        
        public InsertarPacientesRequest(Aplicacion_Caja_Hospital.SN.InsertarPacientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarPacientesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DocumentoIdentidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime Fechanacimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string deuda;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string direccion;
        
        public InsertarPacientesRequestBody() {
        }
        
        public InsertarPacientesRequestBody(string Nombres, string Apellidos, string DocumentoIdentidad, System.DateTime Fechanacimiento, string sexo, string deuda, string direccion) {
            this.Nombres = Nombres;
            this.Apellidos = Apellidos;
            this.DocumentoIdentidad = DocumentoIdentidad;
            this.Fechanacimiento = Fechanacimiento;
            this.sexo = sexo;
            this.deuda = deuda;
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarPacientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarPacientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aplicacion_Caja_Hospital.SN.InsertarPacientesResponseBody Body;
        
        public InsertarPacientesResponse() {
        }
        
        public InsertarPacientesResponse(Aplicacion_Caja_Hospital.SN.InsertarPacientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarPacientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertarPacientesResult;
        
        public InsertarPacientesResponseBody() {
        }
        
        public InsertarPacientesResponseBody(bool InsertarPacientesResult) {
            this.InsertarPacientesResult = InsertarPacientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pacientecajaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pacientecaja", Namespace="http://tempuri.org/", Order=0)]
        public Aplicacion_Caja_Hospital.SN.pacientecajaRequestBody Body;
        
        public pacientecajaRequest() {
        }
        
        public pacientecajaRequest(Aplicacion_Caja_Hospital.SN.pacientecajaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class pacientecajaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DocumentoIdentidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idpaciente;
        
        public pacientecajaRequestBody() {
        }
        
        public pacientecajaRequestBody(string Nombre, string DocumentoIdentidad, int idpaciente) {
            this.Nombre = Nombre;
            this.DocumentoIdentidad = DocumentoIdentidad;
            this.idpaciente = idpaciente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pacientecajaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pacientecajaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aplicacion_Caja_Hospital.SN.pacientecajaResponseBody Body;
        
        public pacientecajaResponse() {
        }
        
        public pacientecajaResponse(Aplicacion_Caja_Hospital.SN.pacientecajaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class pacientecajaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool pacientecajaResult;
        
        public pacientecajaResponseBody() {
        }
        
        public pacientecajaResponseBody(bool pacientecajaResult) {
            this.pacientecajaResult = pacientecajaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginPacientecajaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginPacientecaja", Namespace="http://tempuri.org/", Order=0)]
        public Aplicacion_Caja_Hospital.SN.loginPacientecajaRequestBody Body;
        
        public loginPacientecajaRequest() {
        }
        
        public loginPacientecajaRequest(Aplicacion_Caja_Hospital.SN.loginPacientecajaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginPacientecajaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Paciente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DocumentoIdentidad;
        
        public loginPacientecajaRequestBody() {
        }
        
        public loginPacientecajaRequestBody(string Paciente, string DocumentoIdentidad) {
            this.Paciente = Paciente;
            this.DocumentoIdentidad = DocumentoIdentidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginPacientecajaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginPacientecajaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aplicacion_Caja_Hospital.SN.loginPacientecajaResponseBody Body;
        
        public loginPacientecajaResponse() {
        }
        
        public loginPacientecajaResponse(Aplicacion_Caja_Hospital.SN.loginPacientecajaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginPacientecajaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int loginPacientecajaResult;
        
        public loginPacientecajaResponseBody() {
        }
        
        public loginPacientecajaResponseBody(int loginPacientecajaResult) {
            this.loginPacientecajaResult = loginPacientecajaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarPacienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarPaciente", Namespace="http://tempuri.org/", Order=0)]
        public Aplicacion_Caja_Hospital.SN.RegistrarPacienteRequestBody Body;
        
        public RegistrarPacienteRequest() {
        }
        
        public RegistrarPacienteRequest(Aplicacion_Caja_Hospital.SN.RegistrarPacienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarPacienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Aplicacion_Caja_Hospital.SN.Paciente pacientes;
        
        public RegistrarPacienteRequestBody() {
        }
        
        public RegistrarPacienteRequestBody(Aplicacion_Caja_Hospital.SN.Paciente pacientes) {
            this.pacientes = pacientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarPacienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarPacienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aplicacion_Caja_Hospital.SN.RegistrarPacienteResponseBody Body;
        
        public RegistrarPacienteResponse() {
        }
        
        public RegistrarPacienteResponse(Aplicacion_Caja_Hospital.SN.RegistrarPacienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarPacienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegistrarPacienteResult;
        
        public RegistrarPacienteResponseBody() {
        }
        
        public RegistrarPacienteResponseBody(bool RegistrarPacienteResult) {
            this.RegistrarPacienteResult = RegistrarPacienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AumentarCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AumentarCuenta", Namespace="http://tempuri.org/", Order=0)]
        public Aplicacion_Caja_Hospital.SN.AumentarCuentaRequestBody Body;
        
        public AumentarCuentaRequest() {
        }
        
        public AumentarCuentaRequest(Aplicacion_Caja_Hospital.SN.AumentarCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AumentarCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DocumentoIdentidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DescripcionProcedimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float aumentar;
        
        public AumentarCuentaRequestBody() {
        }
        
        public AumentarCuentaRequestBody(string Nombres, string DocumentoIdentidad, string DescripcionProcedimiento, float aumentar) {
            this.Nombres = Nombres;
            this.DocumentoIdentidad = DocumentoIdentidad;
            this.DescripcionProcedimiento = DescripcionProcedimiento;
            this.aumentar = aumentar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AumentarCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AumentarCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aplicacion_Caja_Hospital.SN.AumentarCuentaResponseBody Body;
        
        public AumentarCuentaResponse() {
        }
        
        public AumentarCuentaResponse(Aplicacion_Caja_Hospital.SN.AumentarCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AumentarCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AumentarCuentaResult;
        
        public AumentarCuentaResponseBody() {
        }
        
        public AumentarCuentaResponseBody(bool AumentarCuentaResult) {
            this.AumentarCuentaResult = AumentarCuentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarCuenta", Namespace="http://tempuri.org/", Order=0)]
        public Aplicacion_Caja_Hospital.SN.PagarCuentaRequestBody Body;
        
        public PagarCuentaRequest() {
        }
        
        public PagarCuentaRequest(Aplicacion_Caja_Hospital.SN.PagarCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DocumentoIdentidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DescripcionProcedimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float pagar;
        
        public PagarCuentaRequestBody() {
        }
        
        public PagarCuentaRequestBody(string Nombres, string DocumentoIdentidad, string DescripcionProcedimiento, float pagar) {
            this.Nombres = Nombres;
            this.DocumentoIdentidad = DocumentoIdentidad;
            this.DescripcionProcedimiento = DescripcionProcedimiento;
            this.pagar = pagar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Aplicacion_Caja_Hospital.SN.PagarCuentaResponseBody Body;
        
        public PagarCuentaResponse() {
        }
        
        public PagarCuentaResponse(Aplicacion_Caja_Hospital.SN.PagarCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PagarCuentaResult;
        
        public PagarCuentaResponseBody() {
        }
        
        public PagarCuentaResponseBody(bool PagarCuentaResult) {
            this.PagarCuentaResult = PagarCuentaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PacientesSoapChannel : Aplicacion_Caja_Hospital.SN.PacientesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PacientesSoapClient : System.ServiceModel.ClientBase<Aplicacion_Caja_Hospital.SN.PacientesSoap>, Aplicacion_Caja_Hospital.SN.PacientesSoap {
        
        public PacientesSoapClient() {
        }
        
        public PacientesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PacientesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacientesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PacientesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aplicacion_Caja_Hospital.SN.InsertarPacientesResponse Aplicacion_Caja_Hospital.SN.PacientesSoap.InsertarPacientes(Aplicacion_Caja_Hospital.SN.InsertarPacientesRequest request) {
            return base.Channel.InsertarPacientes(request);
        }
        
        public bool InsertarPacientes(string Nombres, string Apellidos, string DocumentoIdentidad, System.DateTime Fechanacimiento, string sexo, string deuda, string direccion) {
            Aplicacion_Caja_Hospital.SN.InsertarPacientesRequest inValue = new Aplicacion_Caja_Hospital.SN.InsertarPacientesRequest();
            inValue.Body = new Aplicacion_Caja_Hospital.SN.InsertarPacientesRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.DocumentoIdentidad = DocumentoIdentidad;
            inValue.Body.Fechanacimiento = Fechanacimiento;
            inValue.Body.sexo = sexo;
            inValue.Body.deuda = deuda;
            inValue.Body.direccion = direccion;
            Aplicacion_Caja_Hospital.SN.InsertarPacientesResponse retVal = ((Aplicacion_Caja_Hospital.SN.PacientesSoap)(this)).InsertarPacientes(inValue);
            return retVal.Body.InsertarPacientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.InsertarPacientesResponse> Aplicacion_Caja_Hospital.SN.PacientesSoap.InsertarPacientesAsync(Aplicacion_Caja_Hospital.SN.InsertarPacientesRequest request) {
            return base.Channel.InsertarPacientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.InsertarPacientesResponse> InsertarPacientesAsync(string Nombres, string Apellidos, string DocumentoIdentidad, System.DateTime Fechanacimiento, string sexo, string deuda, string direccion) {
            Aplicacion_Caja_Hospital.SN.InsertarPacientesRequest inValue = new Aplicacion_Caja_Hospital.SN.InsertarPacientesRequest();
            inValue.Body = new Aplicacion_Caja_Hospital.SN.InsertarPacientesRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Apellidos = Apellidos;
            inValue.Body.DocumentoIdentidad = DocumentoIdentidad;
            inValue.Body.Fechanacimiento = Fechanacimiento;
            inValue.Body.sexo = sexo;
            inValue.Body.deuda = deuda;
            inValue.Body.direccion = direccion;
            return ((Aplicacion_Caja_Hospital.SN.PacientesSoap)(this)).InsertarPacientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aplicacion_Caja_Hospital.SN.pacientecajaResponse Aplicacion_Caja_Hospital.SN.PacientesSoap.pacientecaja(Aplicacion_Caja_Hospital.SN.pacientecajaRequest request) {
            return base.Channel.pacientecaja(request);
        }
        
        public bool pacientecaja(string Nombre, string DocumentoIdentidad, int idpaciente) {
            Aplicacion_Caja_Hospital.SN.pacientecajaRequest inValue = new Aplicacion_Caja_Hospital.SN.pacientecajaRequest();
            inValue.Body = new Aplicacion_Caja_Hospital.SN.pacientecajaRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.DocumentoIdentidad = DocumentoIdentidad;
            inValue.Body.idpaciente = idpaciente;
            Aplicacion_Caja_Hospital.SN.pacientecajaResponse retVal = ((Aplicacion_Caja_Hospital.SN.PacientesSoap)(this)).pacientecaja(inValue);
            return retVal.Body.pacientecajaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.pacientecajaResponse> Aplicacion_Caja_Hospital.SN.PacientesSoap.pacientecajaAsync(Aplicacion_Caja_Hospital.SN.pacientecajaRequest request) {
            return base.Channel.pacientecajaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.pacientecajaResponse> pacientecajaAsync(string Nombre, string DocumentoIdentidad, int idpaciente) {
            Aplicacion_Caja_Hospital.SN.pacientecajaRequest inValue = new Aplicacion_Caja_Hospital.SN.pacientecajaRequest();
            inValue.Body = new Aplicacion_Caja_Hospital.SN.pacientecajaRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.DocumentoIdentidad = DocumentoIdentidad;
            inValue.Body.idpaciente = idpaciente;
            return ((Aplicacion_Caja_Hospital.SN.PacientesSoap)(this)).pacientecajaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aplicacion_Caja_Hospital.SN.loginPacientecajaResponse Aplicacion_Caja_Hospital.SN.PacientesSoap.loginPacientecaja(Aplicacion_Caja_Hospital.SN.loginPacientecajaRequest request) {
            return base.Channel.loginPacientecaja(request);
        }
        
        public int loginPacientecaja(string Paciente, string DocumentoIdentidad) {
            Aplicacion_Caja_Hospital.SN.loginPacientecajaRequest inValue = new Aplicacion_Caja_Hospital.SN.loginPacientecajaRequest();
            inValue.Body = new Aplicacion_Caja_Hospital.SN.loginPacientecajaRequestBody();
            inValue.Body.Paciente = Paciente;
            inValue.Body.DocumentoIdentidad = DocumentoIdentidad;
            Aplicacion_Caja_Hospital.SN.loginPacientecajaResponse retVal = ((Aplicacion_Caja_Hospital.SN.PacientesSoap)(this)).loginPacientecaja(inValue);
            return retVal.Body.loginPacientecajaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.loginPacientecajaResponse> Aplicacion_Caja_Hospital.SN.PacientesSoap.loginPacientecajaAsync(Aplicacion_Caja_Hospital.SN.loginPacientecajaRequest request) {
            return base.Channel.loginPacientecajaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.loginPacientecajaResponse> loginPacientecajaAsync(string Paciente, string DocumentoIdentidad) {
            Aplicacion_Caja_Hospital.SN.loginPacientecajaRequest inValue = new Aplicacion_Caja_Hospital.SN.loginPacientecajaRequest();
            inValue.Body = new Aplicacion_Caja_Hospital.SN.loginPacientecajaRequestBody();
            inValue.Body.Paciente = Paciente;
            inValue.Body.DocumentoIdentidad = DocumentoIdentidad;
            return ((Aplicacion_Caja_Hospital.SN.PacientesSoap)(this)).loginPacientecajaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aplicacion_Caja_Hospital.SN.RegistrarPacienteResponse Aplicacion_Caja_Hospital.SN.PacientesSoap.RegistrarPaciente(Aplicacion_Caja_Hospital.SN.RegistrarPacienteRequest request) {
            return base.Channel.RegistrarPaciente(request);
        }
        
        public bool RegistrarPaciente(Aplicacion_Caja_Hospital.SN.Paciente pacientes) {
            Aplicacion_Caja_Hospital.SN.RegistrarPacienteRequest inValue = new Aplicacion_Caja_Hospital.SN.RegistrarPacienteRequest();
            inValue.Body = new Aplicacion_Caja_Hospital.SN.RegistrarPacienteRequestBody();
            inValue.Body.pacientes = pacientes;
            Aplicacion_Caja_Hospital.SN.RegistrarPacienteResponse retVal = ((Aplicacion_Caja_Hospital.SN.PacientesSoap)(this)).RegistrarPaciente(inValue);
            return retVal.Body.RegistrarPacienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.RegistrarPacienteResponse> Aplicacion_Caja_Hospital.SN.PacientesSoap.RegistrarPacienteAsync(Aplicacion_Caja_Hospital.SN.RegistrarPacienteRequest request) {
            return base.Channel.RegistrarPacienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.RegistrarPacienteResponse> RegistrarPacienteAsync(Aplicacion_Caja_Hospital.SN.Paciente pacientes) {
            Aplicacion_Caja_Hospital.SN.RegistrarPacienteRequest inValue = new Aplicacion_Caja_Hospital.SN.RegistrarPacienteRequest();
            inValue.Body = new Aplicacion_Caja_Hospital.SN.RegistrarPacienteRequestBody();
            inValue.Body.pacientes = pacientes;
            return ((Aplicacion_Caja_Hospital.SN.PacientesSoap)(this)).RegistrarPacienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aplicacion_Caja_Hospital.SN.AumentarCuentaResponse Aplicacion_Caja_Hospital.SN.PacientesSoap.AumentarCuenta(Aplicacion_Caja_Hospital.SN.AumentarCuentaRequest request) {
            return base.Channel.AumentarCuenta(request);
        }
        
        public bool AumentarCuenta(string Nombres, string DocumentoIdentidad, string DescripcionProcedimiento, float aumentar) {
            Aplicacion_Caja_Hospital.SN.AumentarCuentaRequest inValue = new Aplicacion_Caja_Hospital.SN.AumentarCuentaRequest();
            inValue.Body = new Aplicacion_Caja_Hospital.SN.AumentarCuentaRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.DocumentoIdentidad = DocumentoIdentidad;
            inValue.Body.DescripcionProcedimiento = DescripcionProcedimiento;
            inValue.Body.aumentar = aumentar;
            Aplicacion_Caja_Hospital.SN.AumentarCuentaResponse retVal = ((Aplicacion_Caja_Hospital.SN.PacientesSoap)(this)).AumentarCuenta(inValue);
            return retVal.Body.AumentarCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.AumentarCuentaResponse> Aplicacion_Caja_Hospital.SN.PacientesSoap.AumentarCuentaAsync(Aplicacion_Caja_Hospital.SN.AumentarCuentaRequest request) {
            return base.Channel.AumentarCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.AumentarCuentaResponse> AumentarCuentaAsync(string Nombres, string DocumentoIdentidad, string DescripcionProcedimiento, float aumentar) {
            Aplicacion_Caja_Hospital.SN.AumentarCuentaRequest inValue = new Aplicacion_Caja_Hospital.SN.AumentarCuentaRequest();
            inValue.Body = new Aplicacion_Caja_Hospital.SN.AumentarCuentaRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.DocumentoIdentidad = DocumentoIdentidad;
            inValue.Body.DescripcionProcedimiento = DescripcionProcedimiento;
            inValue.Body.aumentar = aumentar;
            return ((Aplicacion_Caja_Hospital.SN.PacientesSoap)(this)).AumentarCuentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aplicacion_Caja_Hospital.SN.PagarCuentaResponse Aplicacion_Caja_Hospital.SN.PacientesSoap.PagarCuenta(Aplicacion_Caja_Hospital.SN.PagarCuentaRequest request) {
            return base.Channel.PagarCuenta(request);
        }
        
        public bool PagarCuenta(string Nombres, string DocumentoIdentidad, string DescripcionProcedimiento, float pagar) {
            Aplicacion_Caja_Hospital.SN.PagarCuentaRequest inValue = new Aplicacion_Caja_Hospital.SN.PagarCuentaRequest();
            inValue.Body = new Aplicacion_Caja_Hospital.SN.PagarCuentaRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.DocumentoIdentidad = DocumentoIdentidad;
            inValue.Body.DescripcionProcedimiento = DescripcionProcedimiento;
            inValue.Body.pagar = pagar;
            Aplicacion_Caja_Hospital.SN.PagarCuentaResponse retVal = ((Aplicacion_Caja_Hospital.SN.PacientesSoap)(this)).PagarCuenta(inValue);
            return retVal.Body.PagarCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.PagarCuentaResponse> Aplicacion_Caja_Hospital.SN.PacientesSoap.PagarCuentaAsync(Aplicacion_Caja_Hospital.SN.PagarCuentaRequest request) {
            return base.Channel.PagarCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aplicacion_Caja_Hospital.SN.PagarCuentaResponse> PagarCuentaAsync(string Nombres, string DocumentoIdentidad, string DescripcionProcedimiento, float pagar) {
            Aplicacion_Caja_Hospital.SN.PagarCuentaRequest inValue = new Aplicacion_Caja_Hospital.SN.PagarCuentaRequest();
            inValue.Body = new Aplicacion_Caja_Hospital.SN.PagarCuentaRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.DocumentoIdentidad = DocumentoIdentidad;
            inValue.Body.DescripcionProcedimiento = DescripcionProcedimiento;
            inValue.Body.pagar = pagar;
            return ((Aplicacion_Caja_Hospital.SN.PacientesSoap)(this)).PagarCuentaAsync(inValue);
        }
    }
}
